### ISSUE TITLE
[RAC] Alert Detail Flyout: Consolidate list of items in summary

### ISSUE THREAD

**Issue by mdefazio** [elastic/stack-design-team#93]
The list of items in the summary is quickly growing.  To provide this as a more focused list, let's consider moving items to a separate section/UI treatment:

- Alert status
- Timestamp
- Rule name
- Severity (Risk score)
- Should also be considered along with rule specific details that should be promoted based on rule type

![image](https://user-images.githubusercontent.com/3756330/129719149-36206fde-27ef-4cad-bd95-2f8ed14865b7.png)

**Comment by katrin-freihofner** [comment]
> Should we provide the option to change the workflow status from this field, similar to how we do it on the Cases view?

Yes, I think that is a good idea. We can reuse the existing component.

> For Observability, is there a drastic difference between rule types? What would be the difference in flyout / fields / highlighted fields for a Logs alert, Metrics alert, Uptime alert? Perhaps a good idea to drop in real data to these wireframes for the various rule types just to make sure the segmentation makes sense.

These are the things that come to my mind:

### Alerts are connected
If you monitor your whole environment with Elastic Observability (and set up the alerts) you will likely get multiple alerts for one incident. Imagine an issue with the piece of infrastructure that one of your databases is running on. You will get at least one alert from the infrastructure level (the machine the database is running on). You will get an alert from the service level, as the database service is slow or not responding at all (latency and/or error alert). Depending on your setup you could also get additional alerts from Uptime, Metrics/Infrastructure, and Logs.
-> All of them have the same root cause. Our plan for the future is to show the connection between these alerts. 

### Flapping alerts
Alerts in Observability can auto-close. This means the rule is no longer true, the alert has recovered. They can also be active and recovered many times in a short period of time -> Flapping alerts. (It could be due to a piece of infrastructure that acts up but because of some automation that is in place and restarts the machine automatically it resolves the issue quickly for a short moment.)

### We have pretty diverse rules and reasons. A few examples:
- A monitor is down X times in the last 5 minutes.
- The CPU of X hosts is > Y.
- There are more than 10,000 log events with log level "error" within the last 5 minutes.
- The error rate is higher than X within the last minute.
- A certificate is expiring in X days.

### An alert can be triggered by 1-n entities
An alert can be triggered by a single entity being down (or acting weird). At the same time, an alert can report that a large part of your infrastructure is down. We want to show which entities are affected (this could be a long list; more helpful would be to show what all of these entities have in common).

**Comment by mdefazio** [comment]
Thanks for this.  

> -> All of them have the same root cause. Our plan for the future is to show the connection between these alerts.

Should we hold off then on trying to show a connection between other alerts?  Or do you think this is worth designing for now?

> We want to show which entities are affected (this could be a long list; more helpful would be to show what all of these entities have in common).

Is this also related to the above comment regarding a connection between alerts?  Should we consider showing the `host.name` field a few ways to account for this possibility?

@monina-n I can imagine this might raise some questions. 😄  Let us know how we can help.

**Comment by ryankeairns** [comment]
Let's bring the short-term focus back to 7.16  as Option 2 seemed to be reaching consensus.

The overall amount of content does seem quite long - especially in the Security case - leaving me with two questions/thoughts:
1. How much visual weight and discoverability should be placed on the enriched data? Should it come first or be in a sort of callout-esque section above the summary?
2. Alternatively (and simpler), consider putting each section in an accordion.

With accordions, the more common and repetitive information could be collapsed, by default. In turn, this could help promote content below the 'summary' section. 

It seems to me the other topics (tabs and detail view) have more time to be discussed and settled, so let's set those aside for a moment and settle on a couple of clear next steps for 7.16.

**Comment by monina-n** [comment]
Discussion for asynchronous feedback as we work through different iterations for the Alert flyout -> https://github.com/elastic/security-design-team/discussions/5
